export type User = {
  id: string;
  name: string;
  username: string;
  avatarSeed: string;
  avatarStyle: string;
  avatarEmoji?: string;
  bio: string;
  status: string;
  lastSeenAt: string;
  createdAt: string;
  isOnline: boolean;
};
export type Chat = {
  id: string;
  kind: string;
  title: string | null;
  updated_at: string;
  pinned: number;
  archived: number;
  unread_count: number;
  last_body?: string;
  last_message_at?: string;
  peer_id?: string;
  peer_name?: string;
  peer_username?: string;
  peer_avatar_seed?: string;
  peer_avatar_style?: string;
  peer_status?: string;
  peer_online?: number;
};
export type Message = {
  id: string;
  chat_id: string;
  sender_id: string;
  body: string;
  reply_to_id?: string | null;
  edited_at?: string | null;
  deleted_at?: string | null;
  pinned?: number;
  created_at: string;
  sender_name: string;
  sender_username: string;
  sender_avatar_seed: string;
  reactions: { emoji: string; count: number; mine: number }[];
};
