name = "cloudgram"
compatibility_date = "2026-09-24"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cloudgram-db"
database_id = "3f92bfcc-a8f1-4a41-b79f-75c18741d1c4"
migrations_dir = "database/migrations"
