PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, username TEXT NOT NULL UNIQUE, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, avatar_seed TEXT NOT NULL, avatar_style TEXT NOT NULL DEFAULT 'aurora', bio TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'offline', last_seen_at TEXT NOT NULL, created_at TEXT NOT NULL, is_online INTEGER NOT NULL DEFAULT 0, privacy_json TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS user_settings (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, theme TEXT NOT NULL DEFAULT 'system', accent TEXT NOT NULL DEFAULT 'violet', language TEXT NOT NULL DEFAULT 'ru', notifications INTEGER NOT NULL DEFAULT 1, sound INTEGER NOT NULL DEFAULT 1, compact_mode INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_blocks (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, blocked_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at TEXT NOT NULL, PRIMARY KEY(user_id,blocked_user_id));
CREATE TABLE IF NOT EXISTS chats (id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('direct','group','channel','saved','ai')), title TEXT, owner_id TEXT REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, last_message_id TEXT, archived INTEGER NOT NULL DEFAULT 0, pinned INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS chat_members (chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL DEFAULT 'member', muted INTEGER NOT NULL DEFAULT 0, unread_count INTEGER NOT NULL DEFAULT 0, last_read_at TEXT, joined_at TEXT NOT NULL, PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE, sender_id TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, reply_to_id TEXT REFERENCES messages(id), forwarded_from_id TEXT REFERENCES messages(id), edited_at TEXT, deleted_at TEXT, pinned INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS message_reactions (message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, emoji TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(message_id,user_id));
CREATE TABLE IF NOT EXISTS groups (chat_id TEXT PRIMARY KEY REFERENCES chats(id) ON DELETE CASCADE, description TEXT NOT NULL DEFAULT '', avatar_seed TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS group_members (chat_id TEXT NOT NULL REFERENCES groups(chat_id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL DEFAULT 'member', can_post INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS channels (chat_id TEXT PRIMARY KEY REFERENCES chats(id) ON DELETE CASCADE, username TEXT UNIQUE, description TEXT NOT NULL DEFAULT '', avatar_seed TEXT NOT NULL, subscriber_count INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS channel_members (chat_id TEXT NOT NULL REFERENCES channels(chat_id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL DEFAULT 'subscriber', joined_at TEXT NOT NULL, PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, payload_json TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, reporter_id TEXT NOT NULL REFERENCES users(id), target_user_id TEXT REFERENCES users(id), message_id TEXT REFERENCES messages(id), reason TEXT NOT NULL, details TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, user_agent TEXT NOT NULL DEFAULT '', ip_hash TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS username_index (username TEXT PRIMARY KEY, user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS ai_conversations (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL DEFAULT 'Cloud AI', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ai_messages (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('user','assistant','system')), body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_username_prefix ON username_index(username COLLATE NOCASE);
CREATE INDEX IF NOT EXISTS idx_chat_members_user_updated ON chat_members(user_id,chat_id);
CREATE INDEX IF NOT EXISTS idx_chats_updated ON chats(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_chat_created ON messages(chat_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_chat_id ON messages(chat_id,id);
CREATE INDEX IF NOT EXISTS idx_messages_body ON messages(body);
CREATE INDEX IF NOT EXISTS idx_reactions_message ON message_reactions(message_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id,read_at,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_reports_created ON reports(created_at DESC);
